import SectionContainer from "@/components/section-container";
import { TaboutUsLocation } from "@/data/types";
import Link from "next/link";
import Image from "next/image";
import GetIcon from "@/components/icons/getIcon";

export default function AboutLocation({
  iaboutUsLocation
}: {
  iaboutUsLocation: TaboutUsLocation;
}) {
  return (
    <SectionContainer>
      <section className="flex items-center py-20">
        <div className="justify-center flex-1 max-w-6xl px-4 py-4 mx-auto lg:py-6 md:px-6 text-center">
          <h1 className="text-5xl font-bold leading-tight mb-6 ">
            {iaboutUsLocation.title.text1}
            <span className="text-primary">
              {" "}
              {iaboutUsLocation.title.text2}
            </span>
            <div className="mt-1">
              <span className="inline-block w-40 h-1 bg-primary rounded-full"></span>
              <span className="inline-block w-3 h-1 ml-1 bg-primary rounded-full"></span>
              <span className="inline-block w-1 h-1 ml-1 bg-primary rounded-full"></span>
            </div>
          </h1>
          <div className="mt-16 relative max-w-4xl mx-auto">
            <Link
              href={`${iaboutUsLocation.locations[0].cta.href}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className="relative z-20 object-cover w-full rounded-2xl h-96">
                <GetIcon iconName={iaboutUsLocation.locations[0].image} />
              </div>
            </Link>
            <div className="absolute top-0 left-0 items-center justify-center hidden -ml-16 -mt-14 lg:inline-flex">
              <svg
                width="169"
                height="136"
                viewBox="0 0 169 136"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <circle
                  cx="49"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="49"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="121"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="73"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="145"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="29"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="50"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="71"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="92"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="25"
                  cy="113"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="28"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="49"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="70"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="91"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
                <circle
                  cx="97"
                  cy="112"
                  r="5"
                  fill="#6b7290"
                  fillOpacity="0.32"
                />
              </svg>
            </div>
            <div className="bottom-0 z-40 mt-10 -mb-20 lg:absolute lg:right-0 lg:-mr-10 lg:mt-0 ">
              <div className="w-full p-4 border bg-bgprimary shadow-md lg:w-96 rounded-xl">
                <h2 className="mb-4 text-2xl font-bold text-primary ">
                  {iaboutUsLocation.locations[0].area}
                </h2>
                <p className="pb-4 mb-4 text-texttertiary">
                  {iaboutUsLocation.locations[0].address}
                </p>
                <Link
                  target="_blank"
                  rel="noopener noreferrer"
                  href={`${iaboutUsLocation.locations[0].cta.href}`}
                  className="px-4 py-2 text-sm text-white transition-all transform bg-primary rounded-lg hover:bg-tertiary  hover:text-white"
                >
                  {iaboutUsLocation.locations[0].cta.text}
                </Link>
              </div>
            </div>
          </div>
          <div className="mt-16 relative max-w-4xl mx-auto">
            <Link
              href={`${iaboutUsLocation.locations[1].cta.href}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className="relative z-20 object-cover w-full rounded-2xl h-96">
                <GetIcon iconName={iaboutUsLocation.locations[1].image} />
              </div>
            </Link>
            <div className="bottom-0 z-40 mt-10 -mb-20 lg:absolute lg:left-0 lg:-ml-10 lg:mt-0 ">
              <div className="w-full p-4 border bg-bgprimary shadow-md lg:w-96 rounded-xl">
                <h2 className="mb-4 text-2xl font-bold text-primary ">
                  {iaboutUsLocation.locations[1].area}
                </h2>
                <p className="pb-4 mb-4 text-texttertiary">
                  {iaboutUsLocation.locations[1].address}
                </p>
                <Link
                  target="_blank"
                  rel="noopener noreferrer"
                  href={`${iaboutUsLocation.locations[1].cta.href}`}
                  className="px-4 py-2 text-sm text-white transition-all transform bg-primary rounded-lg hover:bg-tertiary  hover:text-white"
                >
                  {iaboutUsLocation.locations[1].cta.text}
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </SectionContainer>
  );
}
